# Generated by Django 4.2.9 on 2026-01-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN_SYSTEME', 'Administrateur Système'), ('AGENT_ADMINISTRATIF', 'Agent Administratif'), ('RESPONSABLE_LOGISTIQUE', 'Responsable Logistique'), ('COMPTABLE', 'Comptable / Facturation'), ('DIRECTION', 'Direction'), ('CHAUFFEUR', 'Chauffeur')], default='AGENT_ADMINISTRATIF', max_length=50, verbose_name='Rôle'),
        ),
        migrations.AlterModelTable(
            name='customuser',
            table=None,
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
