# Generated by Django 6.0.1 on 2026-01-10 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chauffeur_client_destination_expedition_tarification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, null=True, unique=True)),
                ('date_facture', models.DateField(blank=True, null=True)),
                ('total_ht', models.FloatField(blank=True, null=True)),
                ('montant_tva', models.FloatField(blank=True, null=True)),
                ('total_ttc', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'facture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactureExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'facture_expedition',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('mode_paiement', models.CharField(blank=True, max_length=100, null=True)),
                ('montant', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'paiement',
                'managed': False,
            },
        ),
    ]
