# Generated by Django 6.0.1 on 2026-01-09 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('libelle', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'role',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'utilisateur',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('action_type', models.CharField(choices=[('LOGIN_SUCCESS', 'Connexion réussie'), ('LOGIN_FAILED', 'Connexion échouée'), ('LOGOUT', 'Déconnexion'), ('USER_CREATED', 'Utilisateur créé'), ('USER_UPDATED', 'Utilisateur modifié'), ('USER_ACTIVATED', 'Utilisateur activé'), ('USER_DEACTIVATED', 'Utilisateur désactivé'), ('PASSWORD_RESET', 'Mot de passe réinitialisé'), ('ACCESS_DENIED', 'Accès refusé')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, db_column='utilisateur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.utilisateur')),
            ],
            options={
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx'), models.Index(fields=['user', '-timestamp'], name='audit_log_utilisa_c2c6b3_idx'), models.Index(fields=['action_type', '-timestamp'], name='audit_log_action__ce4ce4_idx')],
            },
        ),
    ]
