# Generated by Django 4.2.9 on 2026-01-24 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_chauffeur_options_alter_client_options_and_more'),
    ]

    operations = [
    ]
