# Generated by Django 4.2.9 on 2026-01-24
#
# The base SQLite schema is often initialized from db/schema.sql which already
# contains a `reclamation` table. This migration:
# - adds optional `type_service_id` if missing
# - creates `reclamation_expedition` join table for "1..N colis"
# - updates Django's migration state

from django.db import migrations, models
import django.db.models.deletion


def _ensure_sqlite_reclamation_schema(apps, schema_editor):
    if schema_editor.connection.vendor != 'sqlite':
        return

    def cols(table_name: str) -> set[str]:
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(f"PRAGMA table_info({table_name});")
            return {row[1] for row in cursor.fetchall()}

    with schema_editor.connection.cursor() as cursor:
        # Ensure base table exists (fresh DB without schema.sql)
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS reclamation (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                client_id integer NULL,
                objet text NULL,
                description text NULL,
                date_reclamation date NULL,
                statut text NULL,
                expedition_id integer NULL,
                facture_id integer NULL,
                traite_par integer NULL,
                date_resolution date NULL,
                type_service_id bigint NULL
            );
            """
        )

        # Ensure reclamation.type_service_id exists (service spécifique)
        try:
            present = cols('reclamation')
        except Exception:
            present = set()

        if 'type_service_id' not in present:
            cursor.execute("ALTER TABLE reclamation ADD COLUMN type_service_id bigint NULL;")

        # Ensure join table exists (un ou plusieurs colis)
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS reclamation_expedition (
                id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                reclamation_id bigint NOT NULL REFERENCES reclamation(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                expedition_id bigint NOT NULL REFERENCES expedition(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                UNIQUE(reclamation_id, expedition_id)
            );
            """
        )

        cursor.execute("CREATE INDEX IF NOT EXISTS reclamation_expedition_reclamation_idx ON reclamation_expedition (reclamation_id);")
        cursor.execute("CREATE INDEX IF NOT EXISTS reclamation_expedition_expedition_idx ON reclamation_expedition (expedition_id);")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_incidents_alertes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_ensure_sqlite_reclamation_schema, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.CreateModel(
                    name='Reclamation',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('objet', models.TextField(blank=True, null=True)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('date_reclamation', models.DateField(blank=True, null=True)),
                        ('statut', models.CharField(blank=True, choices=[('EN_COURS', 'En cours'), ('RESOLUE', 'Résolue'), ('ANNULEE', 'Annulée')], default='EN_COURS', max_length=20, null=True)),
                        ('date_resolution', models.DateField(blank=True, null=True)),
                        ('client', models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client')),
                        ('expedition', models.ForeignKey(blank=True, db_column='expedition_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_principales', to='core.expedition')),
                        ('facture', models.ForeignKey(blank=True, db_column='facture_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facture')),
                        ('type_service', models.ForeignKey(blank=True, db_column='type_service_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.typeservice')),
                        ('traite_par', models.ForeignKey(blank=True, db_column='traite_par', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reclamations_traitees', to='core.utilisateur')),
                    ],
                    options={
                        'db_table': 'reclamation',
                        'managed': True,
                        'ordering': ['-date_reclamation', '-id'],
                    },
                ),
                migrations.CreateModel(
                    name='ReclamationExpedition',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('expedition', models.ForeignKey(db_column='expedition_id', on_delete=django.db.models.deletion.CASCADE, to='core.expedition')),
                        ('reclamation', models.ForeignKey(db_column='reclamation_id', on_delete=django.db.models.deletion.CASCADE, to='core.reclamation')),
                    ],
                    options={
                        'db_table': 'reclamation_expedition',
                        'managed': True,
                        'unique_together': {('reclamation', 'expedition')},
                    },
                ),
                migrations.AddField(
                    model_name='reclamation',
                    name='expeditions',
                    field=models.ManyToManyField(blank=True, related_name='reclamations', through='core.ReclamationExpedition', to='core.expedition'),
                ),
                migrations.AddIndex(
                    model_name='reclamation',
                    index=models.Index(fields=['client', '-date_reclamation'], name='reclamation_client__c5c8a1_idx'),
                ),
                migrations.AddIndex(
                    model_name='reclamation',
                    index=models.Index(fields=['statut', '-date_reclamation'], name='reclamation_statut_3c0370_idx'),
                ),
            ],
        ),
    ]
