# Generated by Django 4.2.9 on 2026-01-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_role_field_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.destination'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, db_column='tournee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='core.tournee'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='type_service',
            field=models.ForeignKey(db_column='type_service_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeservice'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='factureexpedition',
            name='expedition',
            field=models.ForeignKey(db_column='expedition_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.expedition'),
        ),
        migrations.AddField(
            model_name='factureexpedition',
            name='facture',
            field=models.ForeignKey(db_column='facture_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(blank=True, db_column='facture_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facture'),
        ),
        migrations.AddField(
            model_name='tarification',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.destination'),
        ),
        migrations.AddField(
            model_name='tarification',
            name='type_service',
            field=models.ForeignKey(db_column='type_service_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeservice'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(db_column='chauffeur_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='points_passage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(db_column='vehicule_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vehicule'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='chauffeur',
            field=models.ForeignKey(blank=True, db_column='chauffeur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='expedition',
            field=models.ForeignKey(db_column='expedition_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='core.expedition'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='tournee',
            field=models.ForeignKey(blank=True, db_column='tournee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournee'),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.PROTECT, to='core.role'),
        ),
        migrations.AlterUniqueTogether(
            name='factureexpedition',
            unique_together={('facture', 'expedition')},
        ),
    ]
