# Generated by Django 4.2.9 on 2026-01-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_noop_migration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='alerte',
            new_name='alerte_destina_2e1ecc_idx',
            old_name='alerte_destina_9b3007_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incident_created_a21481_idx',
            old_name='incident_created__3e51bc_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incident_type_in_1ca9e9_idx',
            old_name='incident_type_in_9ad5f3_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incident_expedit_f9004d_idx',
            old_name='incident_expediti_dbb83c_idx',
        ),
        migrations.RenameIndex(
            model_name='incident',
            new_name='incident_tournee_389923_idx',
            old_name='incident_tournee_7b848d_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='password_re_token_h_a495e0_idx',
            old_name='password_r_token_ha_29a480_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='password_re_expires_214fae_idx',
            old_name='password_r_expires_efc209_idx',
        ),
        migrations.RenameIndex(
            model_name='passwordresettoken',
            new_name='password_re_utilisa_d98129_idx',
            old_name='password_r_user_id_0bb7a4_idx',
        ),
        migrations.RenameIndex(
            model_name='reclamation',
            new_name='reclamation_client__91f9d2_idx',
            old_name='reclamation_client__c5c8a1_idx',
        ),
        migrations.RenameIndex(
            model_name='reclamation',
            new_name='reclamation_statut_faef6e_idx',
            old_name='reclamation_statut_3c0370_idx',
        ),
        migrations.AddField(
            model_name='expedition',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.destination'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='tournee',
            field=models.ForeignKey(blank=True, db_column='tournee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='core.tournee'),
        ),
        migrations.AddField(
            model_name='expedition',
            name='type_service',
            field=models.ForeignKey(db_column='type_service_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeservice'),
        ),
        migrations.AddField(
            model_name='facture',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.client'),
        ),
        migrations.AddField(
            model_name='factureexpedition',
            name='expedition',
            field=models.ForeignKey(db_column='expedition_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.expedition'),
        ),
        migrations.AddField(
            model_name='factureexpedition',
            name='facture',
            field=models.ForeignKey(db_column='facture_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facture'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='client',
            field=models.ForeignKey(db_column='client_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(blank=True, db_column='facture_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.facture'),
        ),
        migrations.AddField(
            model_name='tarification',
            name='destination',
            field=models.ForeignKey(db_column='destination_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.destination'),
        ),
        migrations.AddField(
            model_name='tarification',
            name='type_service',
            field=models.ForeignKey(db_column='type_service_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.typeservice'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='chauffeur',
            field=models.ForeignKey(db_column='chauffeur_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.utilisateur'),
        ),
        migrations.AddField(
            model_name='tournee',
            name='points_passage',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournee',
            name='vehicule',
            field=models.ForeignKey(db_column='vehicule_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vehicule'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='chauffeur',
            field=models.ForeignKey(blank=True, db_column='chauffeur_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.chauffeur'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='expedition',
            field=models.ForeignKey(db_column='expedition_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='core.expedition'),
        ),
        migrations.AddField(
            model_name='trackingexpedition',
            name='tournee',
            field=models.ForeignKey(blank=True, db_column='tournee_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tournee'),
        ),
        migrations.AlterUniqueTogether(
            name='factureexpedition',
            unique_together={('facture', 'expedition')},
        ),
    ]
